from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page':'/login/'}),
    url(r'^$', 'index.views.index', name='index'),
    url(r'^chpass/$', 'index.views.chpass'),
    url(r'^client/$', 'client.views.index', name='client-index'),
    url(r'^client/client/add/$', 'client.views.newClient', name='client-new'),
    url(r'^client/client/(?P<id>\d+)/$', 'client.views.editClient', name='client-edit'),
    url(r'^client/client/(?P<id>\d+)/delete/$', 'client.views.deleteClient', name='client-delete'),
    url(r'^client/contact/$', 'client.views.indexContact', name='client-contact-index'),
    url(r'^client/contact/add/$', 'client.views.newContact', name='client-contact-new'),
    url(r'^client/contact/(?P<id>\d+)/$', 'client.views.editContact', name='client-contact-edit'),
    url(r'^client/contact/(?P<id>\d+)/delete/$', 'client.views.deleteContact', name='client-contact-delete'),
    url(r'^client/ac/$', 'client.views.indexAdvertisingCampaign', name='client-ac-index'),
    url(r'^client/ac/add/$', 'client.views.newAdvertisingCampaign', name='client-ac-new'),
    url(r'^client/ac/(?P<id>\d+)/$', 'client.views.editAdvertisingCampaign', name='client-ac-edit'),
    url(r'^client/ac/(?P<id>\d+)/delete/$', 'client.views.deleteAdvertisingCampaign', name='client-ac-delete'),
    url(r'^restaurant/$', 'restaurant.views.index', name='restaurant-index'),
    url(r'^restaurant/restaurant/add/$', 'restaurant.views.newRestaurant', name='restaurant-new'),
    url(r'^restaurant/restaurant/(?P<id>\d+)/$', 'restaurant.views.editRestaurant', name='restaurant-edit'),
    url(r'^restaurant/restaurant/(?P<id>\d+)/delete/$', 'restaurant.views.deleteRestaurant', name='restaurant-delete'),
    url(r'^restaurant/contact/$', 'restaurant.views.indexContact', name='contact-index'),
    url(r'^restaurant/contact/add/$', 'restaurant.views.newContact', name='contact-new'),
    url(r'^restaurant/contact/(?P<id>\d+)/$', 'restaurant.views.editContact', name='contact-edit'),
    url(r'^restaurant/contact/(?P<id>\d+)/delete/$', 'restaurant.views.deleteContact', name='contact-delete'),
    url(r'^analytics/$', 'analytics.views.index', name='analytics-index'),
    url(r'^add/contact/?$', 'restaurant.views.newCont'),
)
